### PR TITLE
Fix function naming pattern

### LINKED ISSUE #7: Inconsistency in method name to get player ID
If we have a packet of type `MsgAddPlayer`, the method to get the player ID is called `getPlayerIndex()`. While the same method is called `getPlayerId()` if the packet is of type `MsgRemovePlayer` or `MsgPlayerUpdate`

### PR DESCRIPTION
**Pull request by Adwitiya-Singh**
Fixes #7

### CODE REVIEW

File: src/networking/Packets/MsgAddPlayer.php [hunk 1]
```diff
@@ -38,10 +38,19 @@ class MsgAddPlayer extends GamePacket
 
     /**
      * @since 1.0.0
+     * @deprecated since 1.1, use getPlayerId instead
      */
     public function getPlayerIndex(): int
     {
-        return $this->playerIndex;
+        return $this->getPlayerId();
```
Comment (allejo) [inline src/networking/Packets/MsgAddPlayer.php:47]:
```suggestion
        trigger_deprecation('allejo/bzflag-networking.php', '1.1.0', 'Using "%s" is deprecated, use "%s" instead.', 'getPlayerIndex', 'getPlayerId');

        return $this->getPlayerId();
```

Make a call to `trigger_deprecation()` here please so that dev environments can pick this up in logs.

File: src/networking/Packets/MsgAddPlayer.php [hunk 2]
```diff
@@ -38,10 +38,19 @@ class MsgAddPlayer extends GamePacket
 
     /**
      * @since 1.0.0
+     * @deprecated since 1.1, use getPlayerId instead
```
Comment (allejo) [inline src/networking/Packets/MsgAddPlayer.php]:
```suggestion
     * @deprecated 1.1 use `MsgAddPlayer::getPlayerId()` instead
```

Take a look at the [syntax for `@deprecated`](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#54-deprecated)

**Review by allejo — CHANGES_REQUESTED** [review]

**Review by allejo — APPROVED** [review]
